export const ACTIVITY = 'ACTIVITY'
export const MOVEMENTS = 'MOVEMENTS'
export const PRODUCTS = 'PRODUCTS'
export const PROCESSES = 'PROCESSES'
export const INVENTORIES = 'INVENTORIES'
export const PROCESS_INVENTORY = 'PROCESS_INVENTORY'
export const TASK = 'TASK'
export const TASK_ANCESTORS = 'TASK_ANCESTORS'
export const TASK_DESCENDENTS = 'TASK_DESCENDENTS'
export const TASK_ATTRIBUTE = 'TASK_ATTRIBUTE'
export const MEMBERS = 'MEMBERS'
export const GOALS = 'GOALS'




export const GRAPHS = 'GRAPHS'






export const PACKING_ORDERS = 'PACKING_ORDERS'
export const CONTACTS = 'CONTACTS'
export const INVENTORY_UNITS = 'INVENTORY_UNITS'
export const PACKING_ORDER = 'PACKING_ORDER'
export const ORDER_ITEMS = 'ORDER_ITEMS'


export const ALERT_MISSED_GOALS = 'ALERT_MISSED_GOALS'
export const ALERT_FLAGGED_TASKS = 'ALERT_FLAGGED_TASKS'
export const ALERT_ANOMALOUS_INPUTS = 'ALERT_ANOMALOUS_INPUTS'